version: '2'

services:
  web:
    container_name: weirdy_app
    build: ./app
    volumes:
      - ./app:/app
    links:
      - mongo
    ports:
      - "8083:7331"
    
  mongo:
    container_name: weirdy_db
    image: mongo
    command: mongod --smallfiles
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
